# Generated by Django 4.2 on 2023-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='Название')),
                ('news_anounsment', models.CharField(max_length=250, verbose_name='Анонс')),
                ('news_escription', models.TextField(max_length=50, verbose_name='Статья')),
                ('news_date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
